### ISSUE TITLE
cosmetics echest

### ISSUE THREAD

**Issue by dovis-gif** [dniym/Bending#1]
Unable to remove the "Cosmetics" echest from your inventory, or your even hotbar, or even from one slot to another. Very annoying. Especially because it opens whenever you use a left-click move attached to that slot. 

PS: I omitted the issue template because I was able to accurately describe the problem without it, so it would have been superfluous

**Comment by dniym** [comment]
This is not bending related.  Please report this to RAD/deino as they’re the ones working with that plugin.
