### ISSUE TITLE
Fortify (Sunshine)

### ISSUE THREAD

**Issue by ghost** [dniym/Bending#11]
**Describe the bug**
When activated, fortify creates a glass block cage around you. its a shield. however the walls are panes, and they do not connect to each other, allowing players and mobs to get in.

**To Reproduce**
Activate the move fortify.

**Expected behavior**
Fortify creates a shield that does not let players or mobs through

**Screenshots**
![Screen Shot 2020-02-05 at 7 42 48 PM](https://user-images.githubusercontent.com/5523087/73899020-eaacd400-4850-11ea-8dd7-5f21125d4327.png)

**Additional Information**
Add any other information about the problem here.

**Comment by dniym** [comment]
Fixed #11 changed panes to solid glass blocks.
