### ISSUE TITLE
RocketLaunch (Sunshine)

### ISSUE THREAD

**Issue by ghost** [dniym/Bending#12]
**Describe the bug**
Damage isn't being applied in some cases. When hitting a mob directly, and or hitting near a mob does not deal AOE damage. it seems that damage is only applied when the move hits max distance first.

**To Reproduce**
Just use rocket launch, it gets weird

**Expected behavior**
Hitting a mob or player, or hitting close to mob or player is expected to deal damage.

**Screenshots**

**Additional Information**
Add any other information about the problem here.

**Comment by dniym** [comment]
note: Rockets Bounce, so if you fire them and they hit another block they will change directions.

Fixed rockets not exploding when near other entities.
  1) rockets seem slightly hard to aim but you can spam them pretty fast. 
  2) the explosion has been also improved a little more power than a tnt explosion.

EDIT:  It seems its SUPER easy to hit if you're flying but much harder if your on the ground..

If the rockets should have more detection range let me know there is no collision system for them so it's up to me to detect nearby entities, I can increase the radius it searches if it's too hard to hit with....
