### ISSUE TITLE
Reflection (Sunshine)

### ISSUE THREAD

**Issue by ghost** [dniym/Bending#13]
**Describe the bug**
1 Activating the move disables damage and bending moves reliant on clicking, however you can still sneak and use moves that rely on sneaking, such as combustion.

2 shift clicking to disable reflection does not work. 

3 reflection does not actually stop the player from taking damage from mobs.

**To Reproduce**
1 Activate reflection, select combustion, sneak.

2 enable reflection by clicking, shift click to disable does not work.
**Expected behavior**

3 enable reflection, take damage. suffer and die

**Screenshots**

**Additional Information**
Add any other information about the problem here.

**Comment by dniym** [comment]
All non harmless moves are now prevented when reflection is active.  Also fixed reflection so that shift+click with it selected would actually disable the move.
