### ISSUE TITLE
HeatWave (Sunshine)

### ISSUE THREAD

**Issue by ghost** [dniym/Bending#14]
**Describe the bug**
1 using heatwave while below a block locks players into a stuck state, where the move has to go up completely before disabling.

2 while in the middle of heatwave, you are in the air, you can hold forward and shift. doing such will allow you to spread heatwave in that direction, and will actually disable the falling part of the move, giving the player infinite hover flight.

**To Reproduce**
1 try to use heatwave while below a block. you will just float there for a while

2 activate heatwave, hold forward until you are no longer above flames.

**Expected behavior**
1 perhaps, when hitting a block, heatwave activates there.

2 player stays in place or minimal movement, but fire spout should not be kept on.

**Screenshots**
![Screen Shot 2020-02-05 at 8 10 22 PM](https://user-images.githubusercontent.com/5523087/73900080-36ad4800-4854-11ea-90e9-0e54e507c9f5.png)
![Screen Shot 2020-02-05 at 8 06 29 PM](https://user-images.githubusercontent.com/5523087/73900081-3745de80-4854-11ea-856f-5cb52f28a866.png)
![Screen Shot 2020-02-05 at 8 11 53 PM](https://user-images.githubusercontent.com/5523087/73900084-3745de80-4854-11ea-8d5a-2845e02bde9c.png)

**Additional Information**
Also using fortify before heatwave causes heatwave to stay stuck in your cage until the cage disappears.

**Comment by dniym** [comment]
Should be fixed, but it still seems a little wonky to me the move itself might need some revamping.  If something else is wrong let me know otherwise you should be able to close this ticket.
