### ISSUE TITLE
Ghost (Scarecrow)

### ISSUE THREAD

**Issue by ghost** [dniym/Bending#15]
**Describe the bug**
Sneaking with ghost enables the user to become invisible until the use of a move. however moves that use sneak to activate can be activated without disabling ghost

**To Reproduce**
enable ghost, choose combustion, sneak and activate it

**Expected behavior**
after enabling ghost, dealing any damage or using any moves should disable ghost

**Screenshots**
![Screen Shot 2020-02-05 at 8 23 41 PM](https://user-images.githubusercontent.com/5523087/73900461-732d7380-4855-11ea-8de1-33a23f2953aa.png)

**Additional Information**
sorry for the dark screen shot, accidentally quit my game to take this. that's combustion being used, and I'm in the middle invisible.

**Comment by dniym** [comment]
Ghost mode should now automatically disable whenever any non harmless move is used.
