### ISSUE TITLE
[Ability Request] - Scarecrow Particles

### ISSUE THREAD

**Issue by ghost** [dniym/Bending#17]
**Request**
Simple request to make all the moves of scarecrow use the same particles. You got moves like ghost and teleport that use dark grey colors, then spirit tap which just spits out rainbows. More consistency perhaps?

**Additional information**
1) Consistency will make the entire element feel more professional and polished.
2) sorry for like not using a template, most of it was irrelevant

**Comment by dniym** [comment]
Yeah the rainbow particles used to be black, I’ll look at fixing those, could you list specifically which moves need to be looked at?

**Comment by ghost** [comment]
SpiritTap for sure. TouchOfEvil and DrainLife are both auras, perhaps make them more consistent with each other. DevilsDeal as well.

**Comment by dniym** [comment]
Okay I made touch of evil (orange/black) and drainlife (maroon/black) more similar, just different colored particles.    Likewise spirittap has the same particles with maroon/black particles, and devils deal is maroon/black
