### ISSUE TITLE
Drain (Plants) 

### ISSUE THREAD

**Issue by LifeOfRAD** [dniym/Bending#18]
**Describe the bug**
The discription of Drain states that you can use to drain water from plants to fill bottles or buckets.
this does not work on 1.13 or 1.15 Avatar 

##Works with water source blocks## 
#However uncraftable potion is given not water bottle,Bucket works as expected#

**To Reproduce**
use drain on plants, giving no result

**Expected behavior**
drain water from plants filling up bottles and buckets, if nothing to fill up you use it as a water blast.

**Comment by dniym** [comment]
Fixed #18, water bottles now appear instead of uncraftable potion & drain now works on plants.
