### ISSUE TITLE
Jetblast and Jetblaze are broke

### ISSUE THREAD

**Issue by dovis-gif** [dniym/Bending#19]
**Describe the bug**
Jetblast and Jetblaze do not work.

**To Reproduce**
Try to use these combos. They don't work. Instead, it just activates regular firejet.

**Expected behavior**
Jetblast and Jetblaze should have activated.

**Additional Information**
Interestingly, the cooldown for these combos is activated, even though the move doesn't work.

**Comment by dniym** [comment]
Jetblaze and blast now properly activate when the combo is done, if you notice any further issues with either of these moves please re-open this ticket or create a new one.
