### ISSUE TITLE
vanishing fire particles

### ISSUE THREAD

**Issue by dovis-gif** [dniym/Bending#2]
**Describe the bug**
The render distance for fire moves is very tiny. 

**To Reproduce**
Use a long range fire move

**Expected behavior**
The particles will disappear in your view. They still exist, you just can't see them.

**Additional Information**
This may seem like a tiny tedious unimportant detail, but it's crucially important. Combustion, for example (a crucial weapon in the firebender's arsenal) is rendered completely useless. Firebending depends very very heavily on one's aim and prediction skills, and this is usually what determines the outcome of a fight between two fire pros. I know many firebenders, and they simply will not play on a server where they can't see their particles. I haven't invited them because I don't want them to get a bad impression. I hope that this is fixed soon.

**Comment by dniym** [comment]
Will look into this how much do they need to be increased? Double their current range?

**Comment by dovis-gif** [comment]
The viewing distance should be exactly the same as whatever the range of the actual move is, to facilitate aiming

**Comment by dniym** [comment]
Should be fixed, verified with FireBall, FireBlast and combustion.   If there are other moves experiencing this issue please open a new ticket with a list of any moves that have bugged render distance.

**Comment by dovis-gif** [comment]
Just went on the server and tried it. Not fixed.
