### ISSUE TITLE
Tip for reducing lag  

### ISSUE THREAD

**Issue by dovis-gif** [dniym/Bending#21]
Remove all smoke particles from every firebending move (except combustion, more on that soon).
The smoke particles are unneeded for bending, and inconsistent since some moves have smoke particles while others (firespin, firekick, firewheel) don't. But they do cause a lot of lag for a lot of players (especially moves like jetblaze and fireburst). Although most of these moves are not especially laggy, I think that the cumulative effect of removing smoke particles would be to reduce lag overall.
The only move for which smoke particles should not be removed is combustion, because the smoke is needed to signal when the move is charged and ready to launch (like shockwave and earthsmash). Perhaps we could remove the smoke particles from the beam, but not from the charge.

**Comment by dniym** [comment]
Should be done, if there are particle issues please open a new bug report with the specific move that is having problems.
