### ISSUE TITLE
FireJet Hover

### ISSUE THREAD

**Issue by dovis-gif** [dniym/Bending#23]
**Describe the bug**
Normal FireJet does not work at all.

**To Reproduce**
Left-click with FireJet. 

**Expected behavior**
Instead of propelling forwards, FireJet Hover is activated.

**Additional Information**
FireJet Hover is not activated when you press Shift, like it should be.
Also, there's no cooldown on FireJet Hover, so you can just keep clicking to hop in the air like a bunny

**Comment by dniym** [comment]
Fixed
