### ISSUE TITLE
JetBlast and Jetblaze

### ISSUE THREAD

**Issue by dovis-gif** [dniym/Bending#24]
**Describe the bug**
Jetblast and Jetblaze do not work, at all.

**To Reproduce**
Try to use these moves (tap shift w firejet x 2 > tap shift w blaze/fireshield > left click w firejet).

**Expected behavior**
JetBlast or Jetblaze should have activated

**Additional Information**
When you try to use these moves, you can see "Jetblast" or "Jetblaze" above your slots. So the move apparently activates to some extent, but doesn't work.
P:S I chose to include both Jetblaze and Jetblast in the same report because they both seem to have the same underlying issue, as far as I can tell.

**Comment by dniym** [comment]
These are config related issues, same as on the test server.  Same problem that existed on the test server should be an easy fix.

**Comment by dniym** [comment]
Fixed
