### ISSUE TITLE
Firejet

### ISSUE THREAD

**Issue by dovis-gif** [dniym/Bending#25]
**Describe the bug**
When duration for firejet expires, you seem to stop suddenly, almost as if you ran into an invisible wall. It feels very unnatural.

**To Reproduce**
Use firejet

**Expected behavior**
The end of firejet's duration should be simply the cessation of firejet; that is, you stop propelling forwards. After that, normal gravity should take effect.

**Comment by dniym** [comment]
Yes this is due to your last bug on the test server, you wanted the ability to cancel firejet on demand, once the momentum is applied the point you end up when firejet expires and cancel is almost the same point.  If the momentum is not canceled there’s really no point in having a cancel feature.

**Comment by dniym** [comment]
Closed due to no response from OP.
