### ISSUE TITLE
Fireshield is completely busted

### ISSUE THREAD

**Issue by dovis-gif** [dniym/Bending#3]
**Describe the bug**
Title. Fireshield simply does not work. Neither the move itself nor the particles. Neither the shift version or the clicky version

**To Reproduce**
Try to use fireshield

**Additional Information**
Interestingly, even though fireshield itself is broken, Firewheel (a combo depending on fireshield) is working fine as far as I can tell (though the particles are a bit unorthodox)

**Comment by dniym** [comment]
Should be fixed, the reason firewheel still worked is because you just have to attempt to activate the move or select it in some instances for combos.. The combo does not directly rely on one of the activation moves working.
