### ISSUE TITLE
[Ability Request] - FrostBreath change 

### ISSUE THREAD

**Issue by ghost** [dniym/Bending#4]
**Frost Breath**
The name for the ability you wish to see created or modified.

**It spits out a beam of ice, as long as you sneak**
A descriptive and well worded description of the Ability.

**From the technical side, its obvious that it only works in some biomes, those that have a temperature that only a snow golem can survive in. It also seems this beam does damage but does not seem to apply a status effect of any sort.**
Please fill out as much of the information as you can.   Please do not just put (I don't know or It's up to you) I will likely reject requests that are not well thought out.

1) What element is this ability for? Frost
2) Is this ability OFFENSIVE or DEFENSIVE? Offensive
3) Is it passive or do you have to activate it?   Activate by sneaking.
4) Should there be any animations / particles when the ability is activated?  Current is fine
5) If the ability requires charging, what should that animation look like? N/A
6) Can this ability target other players? Yes
7) Can this ability target NPCs? Yes
8) Can this ability be used on the player that activated it? No
9) How much damage (in hearts) should this move deal or heal (if a healing ability) Current is fine
10) How much cooldown should this move have after being used? Same cool down as FireBreath
11) If this ability needs a source of a specific type to activate, what should that be? should not use source, the bender should be considered the source

**Additional information**
1) Why do you think this move should be added / changed?
This is basically a rebranded version of Fire Breath, but worse. 
This move cannot be used in all biomes like its predecessor and has a significantly longer cool down especially with an element that has so few moves to start with. The restrictions put on this move really put it at a massive disadvantage unless given pros to balance it out. I suggest removing the biome restrictions based on temperature (with the argument being that katana was able to create ice during the agni kai during Sozin's Comet. Very hot environment and she still made ice), and lowering the cool down to about half the current cool down time. Ideally, this move should be on par or a little more powerful than Fire Breath so as to give snowman a little more fire power. 

2) Any other comments you believe to be relevant.
Snowman currently on the test server has 5 moves. No one is going to use snowman if there are only five moves. This suggestion is focusing on making snowman a bit more fair. With so few moves, their moves should be a bit more focused when it comes to damage.

**Comment by dniym** [comment]
Will look at rebalancing this ability somewhat.  Things I can think of would be

1) allowing any water source
2) shorter cooldown vs firebreath
3) chilling / slow effect
4) slight damage bump

**Comment by dovis-gif** [comment]
I have _**a lot**_ of ideas for changing and balancing moves, including frostbreath, and also many ideas for improving snowman. But I think we should focus on bugs now. We need to have a stable, functioning bending system to work with before we get to balancing.

**Comment by dniym** [comment]
1) Removed biome restriction
2) Reduced cooldown from 15 seconds to 5
3) Increased damage to players and mobs to 3 hearts vs 2
