### ISSUE TITLE
Air Moves Fire particles

### ISSUE THREAD

**Issue by LifeOfRAD** [dniym/Bending#5]
**Describe the bug**
when using Air moves such as AirBlade and AirBlast are using Fire Particles

**To Reproduce**
use AirBlade or AirBlast (might be all air moves untested)

**Expected behavior**
air particles not fire

**Comment by LifeOfRAD** [comment]
I also keep getting random fire particles on Torrent too

**Comment by dniym** [comment]
Hmmm alright, I’ll check into this I just worked on particles probably made a typo

**Comment by dniym** [comment]
Should be fixed please create a bug report noting any other moves with incorrect particles.
