### ISSUE TITLE
Fireshield is drunk

### ISSUE THREAD

**Issue by dovis-gif** [dniym/Bending#6]
**Describe the bug**
Title

**To Reproduce**
Use fireshield, both the clicky and the shifty version

**Expected behavior**
Fireshield's radius is **massive**. It basically makes you immortal.

**Screenshots**
https://i.imgur.com/P9MwKaT.png

**Comment by dniym** [comment]
Both are too large?  The click version only has a radius of 3.  So 6x6

**Comment by dovis-gif** [comment]
Click's default radius is 1.5.  3 is what the shift version is supposed to be.

**Comment by dniym** [comment]
Reduced radius of click to 1.5 and 3 to the shift version.
