### ISSUE TITLE
firejet problems

### ISSUE THREAD

**Issue by dovis-gif** [dniym/Bending#7]
1. Jetblast and Jetblaze are completely busted. I imagine that the reason is because firejet's cooldown is activated by hover, which interferes with the combo chain. 

3. Firejet's speed or duration seems small (has it been reduced from the default setting, or does it only seem small in comparison to icejet?). But when you use press shift for firejet hover, and, while continuing to hold shift, left click; then firejet's duration lasts much longer, which is weird.

There are some moves that firebenders can do without, but firejet is not one of them. Firejet and its two twin combos are arguably the most important move a firebender has. It is used to evade attacks, rush opponents, charge other moves, chase after runners, or run away if necessary. But sometimes it can be a disadvantage when used against experienced benders, so it must be used strategically. But all of this is impossible because of these problems. No serious firebender would be able to play on a server where firejet doesn't work smoothly. These bugs are like sand in the gears of a firebending fight. I hope this is fixed soon.

I would recommend that firejet, jetblaze and jetblast are all set to the default settings.

**Comment by dniym** [comment]
Going to rework firejet’s hover to require a shift+click to activate. That should make jetblaze/blast more natural feeling.

**Comment by dniym** [comment]
fixed, firejet now requires a shift click to activate hover mode.
