### ISSUE TITLE
Freedom (Sunshine)

### ISSUE THREAD

**Issue by ghost** [dniym/Bending#9]
**Describe the bug**
Sometimes under certain cases, using Freedom (SunShine) the field does not expand and it will remain a tiny ball of green notes

**To Reproduce**
Sneak to charge Freedom, then jump while charging. Releasing afterwards does not allow the field to expand.

**Expected behavior**
Sneaking to charge, after release. The move's field expands to full range, which is like 5 blocks or so

**Screenshots**
![Screen Shot 2020-02-05 at 3 35 00 PM](https://user-images.githubusercontent.com/5523087/73897998-8b999000-484d-11ea-88f4-64eee671bc56.png)
![Screen Shot 2020-02-05 at 6 33 00 PM](https://user-images.githubusercontent.com/5523087/73898000-8c322680-484d-11ea-8cb7-e00ec9bdbe7c.png)

**Additional Information**
Add any other information about the problem here.

**Comment by dniym** [comment]
for whatever reason I can not seem to reproduce this bug.  Can you reliably cause this to happen?  Jumping and releasing shift seems to have no effect.

**Comment by dniym** [comment]
Fixed: Falling with this move now cancels if you get too far away from where you started the move.   Typically this should only happen if a user jumps off of something.
